site_name: Notes & Projects
site_description: Personal knowledge hub - Notes, projects, and documentation
site_url: https://dsosaa.github.io/overwrked-public/
repo_name: dsosaa/overwrked-public
repo_url: https://github.com/dsosaa/overwrked-public
edit_uri: edit/main/Public/
docs_dir: Public

# Copyright and author information
copyright: Copyright &copy; 2025 overwrked.ai - Built with Material for MkDocs

nav:

theme:
  name: material
  language: en
  features:
    # Navigation enhancements
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.top
    - navigation.tracking
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    
    # Table of contents improvements
    - toc.integrate
    - toc.follow
    
    # Content enhancements
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - content.tabs.link
    - content.tooltips
    - content.footnote.tooltips
    - content.action.edit
    - content.action.view
    
    # Search improvements
    - search.suggest
    - search.highlight
    - search.share
    
    # Header/footer features
    - header.autohide
    - announce.dismiss
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: cyan
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      accent: cyan
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
  font:
    text: Inter
    code: 'JetBrains Mono'
  icon:
    logo: material/book-open-variant
    repo: fontawesome/brands/github
    edit: material/pencil
    view: material/eye
    tag:
      html: fontawesome/brands/html5
      js: fontawesome/brands/js-square
      css: fontawesome/brands/css3-alt
      python: fontawesome/brands/python
      docker: fontawesome/brands/docker
      api: material/api
      database: material/database
      deployment: material/rocket-launch

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/dsosaa
      name: GitHub Profile
    - icon: material/email
      link: mailto:contact@overwrked.ai
      name: Contact Email
  generator: false
  
  # Analytics and tracking with enhanced features
  analytics:
    provider: google
    property: !ENV [GOOGLE_ANALYTICS_KEY, G-XXXXXXXXXX]
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/thumb-up-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback! Help us improve our documentation.
        - icon: material/thumb-down-outline
          name: This page could be improved
          data: 0
          note: >- 
            Thanks for your feedback! Help us improve this page by
            <a href="https://github.com/dsosaa/overwrked-public/issues/new/?title=[Feedback]+{title}+-+{url}" target="_blank" rel="noopener">telling us what you're missing</a>.
  
  # Performance and caching
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
    actions:
      - accept
      - reject
      - manage
  
  # Status and version
  status:
    new: Recently added
    deprecated: Deprecated
  
  # Announcement bar
  announcement: 🚀 New features and documentation updates coming soon!

plugins:
  # Core search functionality with enhanced features
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
      lang:
        - en
  
  # Content organization and management
  - awesome-pages
  - tags
  
  # Social cards generation (Material Insiders feature)
  # Uncomment if using Material for MkDocs Insiders
  # - social:
  #     cards: true
  #     cards_dir: assets/images/social
  #     cards_layout_options:
  #       background_color: "#0d1117"
  #       color: "#e6edf3"
  #       font_family: Inter
  
  # Privacy and GDPR compliance (Material Insiders feature)
  # Uncomment if using Material for MkDocs Insiders
  # - privacy:
  #     enabled: true
  #     cache: true
  #     assets: true
  #     links: true
  #     links_attr_map:
  #       target: _blank
  #       rel: noopener
  
  # Advanced site optimization (Material Insiders feature)
  # Uncomment if using Material for MkDocs Insiders
  # - optimize:
  #     enabled: true
  #     optimize_png: true
  #     optimize_jpg: true
  #     cache: true
      
  # Media and content optimization
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      slide_effect: slide
      width: 100%
      height: auto
      zoomable: true
      draggable: true
      auto_caption: false
      caption_position: bottom
      
  # Site minification
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
        remove_comments: true
        remove_empty_space: true
        reduce_boolean_attributes: true
        
  # Git integration for last updated dates
  - git-revision-date-localized:
      type: timeago
      timezone: America/Los_Angeles
      locale: en
      fallback_to_build_date: true
      enable_creation_date: true
      strict: false
      
  # Performance monitoring and contributor tracking
  - git-committers:
      repository: dsosaa/overwrked-public
      branch: main
      cache_dir: .cache/plugin/git-committers

markdown_extensions:
  # Basic extensions
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - meta
  
  # Advanced PyMdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      auto_title: true
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: dsosaa
      repo: overwrked-public
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - toc:
      permalink: true
      title: On this page
      toc_depth: 3

extra_css:
  - assets/cursor-theme.css
  - assets/enhanced-visuals.css
  - assets/homepage-enhancements.css
  - assets/obsidian-enhancements.css
  - assets/dashboard-styles.css
  - assets/premium-design.css
  - assets/enhanced-components.css
  - assets/sleek-cards.css
  - assets/clean-layout.css
  - assets/enhanced-icons.css
  - assets/obsidian-native-editor.css
  - assets/features-page.css
  - https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200

extra_javascript:
  - https://unpkg.com/mermaid@10.6.1/dist/mermaid.min.js
  - assets/interactive-features.js
  - assets/advanced-interactions.js
  - assets/obsidian-features.js
  - assets/interactive-file-tree.js
  - assets/advanced-features.js
  - assets/obsidian-native-editor.js
  - assets/real-api-integration.js
